### ISSUE TITLE
  You must upgrade your system V8 library to use the JS engine.

### ISSUE THREAD

**Issue by mwylerCH** [brianwdavis/quadrangle#5]
Hi,
quadrangle works fine if the QR code is more or less nicely visible (aka using magick). But otherwise I'm not able to use the JS machine.

 ``` You must upgrade your system V8 library to use the JS engine.```

Would it not be possible to recommend the best way to do that? I'm not getting more then V8 3.14.5.9

Thanks

**Comment by brianwdavis** [comment]
Thanks for the feedback! I'm glad to know other people are finding this package useful.

The error is generated here: https://github.com/brianwdavis/quadrangle/blob/986c52b9cf03cab634921c8a4b62745ab49b574e/R/js_helpers.R#L86

And once that error gets thrown, it should suggest: https://github.com/brianwdavis/quadrangle/blob/3abfa6b57e14372002729adaac699adfc5c57623/R/js_helpers.R#L113

Going to that URL points to:

>Installation from source on Linux requires `libv8`. On Ubuntu / Debian you need to install either `libv8-dev`, or `libnode-dev`. On the latest systems, libv8-dev is actually an alias for `libnode-dev` so they are the same:

> `# Debian and Ubuntu`
> `sudo apt-get install -y libv8-dev`


I ran into this problem that the version of `libv8` included on Ubuntu and Debian distros is only `3.14...`, while the latest is `6.8.275.32-node.55`. Pointing the user to the `{V8}` docs seemed to be the easy fix. Is there something I could do to be clearer?


## Steps to reproduce the fix:

I just tested this on a Docker container: https://hub.docker.com/r/rocker/rstudio

1. local bash:
`docker pull rocker/rstudio`
`docker run -d -p 8787:8787 -e ROOT=TRUE -e PASSWORD=yourpasswordhere rocker/rstudio`

2. go to `localhost:8787` in your local browser and log in with `rstudio` and `yourpasswordhere`, then go to the Terminal pane of Rstudio:
`sudo apt-get update`
`sudo apt-get install libnode-dev`

3. at the R console:
`install.packages("V8")`
`library(V8)`
> `Using V8 engine 6.8.275.32-node.55`

**Comment by brianwdavis** [comment]
If you're having this problem on a non-Ubuntu/Debian OS, please do let me know!

**Comment by mwylerCH** [comment]
Thanks, yes the problem was the old distribution of libv8.

Here I found the solution
https://takehomessage.com/2019/12/10/r-package-v8/
