### ISSUE TITLE
Text encoded in latin1 is not read by qr_scan with force_js = TRUE

### ISSUE THREAD

**Issue by philaris** [brianwdavis/quadrangle#9]
First of all, thank you @brianwdavis for this nice R package!

I have the following issue. I am reading some latin1 encoded text with `force_js` set to `TRUE`. Note that latin1 is the default encoding for QR codes. The issue is that the value of the text returned by qr_scan is empty.

This is how to reproduce the problem:

Save the following file as `latin1_small_umlaut.png`.

![latin1_small_umlaut](https://user-images.githubusercontent.com/9732649/220458066-c37f8fda-9137-4d94-8007-20499dd68457.png)

Then running `qr_scan("latin1_small_umlaut.png", force_js = TRUE)` returns:
```
$values
  id type value
1  1 byte      

$points
  id                      corner   x   y
1  1              topRightCorner 178  12
2  1               topLeftCorner  14  12
3  1           bottomRightCorner 179 177
4  1            bottomLeftCorner  14 177
5  1       topRightFinderPattern 151  40
6  1        topLeftFinderPattern  41  40
7  1     bottomLeftFinderPattern  41 150
8  1 bottomRightAlignmentPattern 128 126
```

This is what is returned from jsQR for the same file:
```
jsQR git:(master) ✗ npx ts-node --project tests/ tests/mine.ts
{
  binaryData: [ 90, 252, 114, 105, 99, 104 ],
  data: '',
  chunks: [ { type: 'byte', bytes: [Array], text: '' } ],
  version: 1,
  location: {
    topRightCorner: { x: 178.5, y: 11.999999999999998 },
    topLeftCorner: { x: 13.589088291253148, y: 12.089088291253143 },
    bottomRightCorner: { x: 178.94834635888412, y: 177.4483463588841 },
    bottomLeftCorner: { x: 13.500000000000004, y: 177.00000000000003 },
    topRightFinderPattern: { x: 151, y: 39.5 },
    topLeftFinderPattern: { x: 41, y: 39.5 },
    bottomLeftFinderPattern: { x: 41, y: 149.5 },
    bottomRightAlignmentPattern: { x: 127.53571428571428, y: 126.03571428571428 }
  }
}
```
Observe that the `text` field is the empty string.

The bytes array component contains `Zürich` encoded in ISO-8859-1 (latin1) where `ü` is encoded as `0xfc` (or 252 in base 10).

This issue is related to this issue: https://github.com/cozmo/jsQR/issues/129

I am thinking of a possible fix in `quadrangle`. The R package has access to the bytes array in `qr_parse_js_`. One could detect an empty text string with a non-empty bytes integer vector and set the text component accordingly. What do you think? I hope to create a pull request.

**Comment by brianwdavis** [comment]
Closed with #10
